name: Titania
version: 1.0
author: Redwoub
main: fr.redwoub.titania.Main
commands:
  bc:
    permission: titania.bc
    permission-message: §cVous n'avez pas la permission d'executer cette commande
  invsee:
    permission-message: §cVous n'avez pas la permission d'executer cette commande
    permission: titania.invsee
  freeze:
    permission: titania.freeze
    permission-message: §cVous n'avez pas la permission d'executer cette commande
  unfreeze:
    permission: titania.unfreeze
    permission-message: §cVous n'avez pas la permission d'executer cette commande
  money:
  menu:
  list:
